Support for Digilent Cora Z7-10 (#146)
* Support for Digilent Cora Z7-10

* Adding goals `cora10vivado` and `cora10vivadobits` to examples/makefile.

* Removing the error Synth 8-6735

ERROR: [Synth 8-6735] net type must be explicitly specified for ... when
default_nettype is none

* Separating failures into categories.

* Updating platform/cora10vivado/README.md